### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by saippuakauppias** [go-shiori/go-readability#18] opened 2021-02-26 09:13 UTC
Added your tool to the benchmark: https://github.com/scrapinghub/article-extraction-benchmark

**Comment by RadhiFadlillah** [comment] 2021-03-01 00:47
Hi, thanks for the link and benchmark :+1: 

It's quite interesting to see `go-readability` has better precision compared to `Readability.js`, especially since `go-readability` is ported line by line from `Readability.js`. I guess the problem is in `JsDom` library that used by Readability.js to parse the web page.

By the way you might be interested with [`go-domdistiller`](https://github.com/markusmobius/go-domdistiller), Go port of the Dom Distiller library which I worked on several months ago. In case you are not familiar with it, Dom Distiller is engine for reader mode in Chrome. So if Firefox use Readability.js, then Chrome use Dom Distiller.

From what I tested so far, go-domdistiller is better than go-readability at extracting images and articles, but a bit slower and not really good when extracting wiki and documentation. I'd love to see it benchmarked properly, but unfortunately I'm a bit busy these days. Someday I guess.

---

By the way, since this is not an issue, I hope you don't mind that I'll close it :smile:

**Closed as completed by RadhiFadlillah** 2021-03-01 00:47 UTC
